### ISSUE TITLE
Camera image not working on first load

### ISSUE THREAD

**Issue by Blackpander** [denysdovhan/vacuum-card#192]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

When I press F5 and refresh my browser the camera image from my vacuum map is not shown.
Also there are some errors regarding the camera in the log. I don't know if that is related.

**Steps to reproduce**

1. Use a camera image in your card.
2. Refresh your browser with F5
3. Check if there is no camera image loading
4. Click on another tab in Home Assistant
5. Click back on the Home tab
6. See your camera image loaded

**Expected behavior**
A card with a working camera image on first load.

**Screenshots**
![image](https://user-images.githubusercontent.com/25155117/110634017-c2a54800-81a9-11eb-9d12-19a6f9466cf2.png)
![image](https://user-images.githubusercontent.com/25155117/110633957-b3be9580-81a9-11eb-8259-7317cbafe3b5.png)
**Versions:**

- Release: 1.18.0
- Browser: Chrome
- Home Assistant Core: core-2021.3.3
- Home Assistant Supervisor: supervisor-2021.03.4

**Comment by grinstantin** [comment]
May/must be fixed in 1.19.1. Check it, please.

**Comment by RoboMagus** [comment]
I noticed the same thing occasionally. However there is an additional concern: the failing load causes a 401 error. I've setup Ipban for some additional security, but this causes loading my dashboard to ban my device every so often, due to the unauthorized requests.
It seems that the initial map load is done using an out of date token, causing the request to be unauthorized.

**Comment by denysdovhan** [comment]
Should be resolved.
