### ISSUE TITLE
fire-dom-event support

### ISSUE THREAD

**Issue by kimme1024** [denysdovhan/vacuum-card#241]
**Is your feature request related to a problem? Please describe.**
I'd like to have a popup when clicking on an action button in the vacuum card so that I can show lovelace-xiaomi-vacuum-map-card. I tried to do this using browser-mod but I can't get it to work. The developer of lovelace-xiaomi-vacuum-map-card assumes that there's no support for fire-dom-event in your card which prevents it from working

**Describe the solution you'd like**
Support for fire-dom-event

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by vlycop** [comment]
Hello !
I would very much like to push this forward. Since https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0 update of Browser_mod, i can't use my vacuum setup.

The issue is that we nolonger can use a service to trigger the popup, but a dom event.
Here is an exemple of what my menu was, i really want that back :(
![image](https://user-images.githubusercontent.com/17001679/135769162-9d69337a-145a-4742-9242-029ff6d84b63.png)
![image](https://user-images.githubusercontent.com/17001679/135769172-c4f51d40-25a5-4e36-b76e-1db7674b8639.png)
The square button trigger a popup with toggle per room, and a start button.
This let me quickly choose what room to clean.

How hard would this be ? i have no knowledge of development and don't realize what i am asking ... but am really want to update browser_mod
Thank you

**Comment by denysdovhan** [comment]
Try using the latest version. Should be addressed there.

**Comment by vlycop** [comment]
Thank you ! i am very happy to have this fixed and will try it soon !
keeping the old Browser_mod working with all the breaking change in HASS was very hard for me

**Comment by vlycop** [comment]
I am confused.
The new way to do this are "shortcut" but they didn't improved from action ?
the doc only allow those option

name | string | Optional | Friendly name of the action, i.e. Clean bedroom.
-- | -- | -- | --
service | string | Optional | A service to call, i.e. script.clean_bedroom.
icon | string | Optional | Any icon for action button.
service_data | object | service_data for service call |  

So this is still stuck to service ? and don't support fire-dom-event or any other action that standard button do ?
Or did i miss a thing ?
I need to be able to change the action type like 
```
shortcuts:
  - name: Room Cleaning
    icon: mdi:texture-box
    action: fire-dom-event
    browser_mod:
      command: toast
      message: Hello, world!
```

**Comment by denysdovhan** [comment]
Got it. Didn't understand the problem at the beginning. Reopening.

**Comment by vlycop** [comment]
Won't lie, the false hope really got me :(
I trully hope this will be easy and quick to fix

Thanks for reopening.

**Comment by vlycop** [comment]
This is still not fixed, i switched card to the mushroom one stacked with a grid of button as a work around, but i would really like to have this upgraded to ha standard instead, it's way more usefull

**Comment by Vaarlion** [comment]
I personally nolonger use this card
