### ISSUE TITLE
Xiaomi Mi Robot Vacuum (STYJ02YM) no information

### ISSUE THREAD

**Issue by stormnetgd** [denysdovhan/vacuum-card#27]
STYJ02YM no information about Filter, Side brush and others.

![vacuum](https://user-images.githubusercontent.com/60716719/81502837-b4b03d80-92e0-11ea-945f-cf963469dd91.png)

**Comment by denysdovhan** [comment]
Any other debug information?

**Comment by Mdleal** [comment]
same. I'm using valetudo mqtt integration for the vac.

![image](https://user-images.githubusercontent.com/691042/81609146-f69eb980-939c-11ea-9d55-59f9be7db9ef.png)

**Comment by krystiancharubin** [comment]
Currently the card is expecting stats attributes to be named `<name>_left`. For example when looking for main brush its expecting `main_brush_left` instead of `mainBrush` that your vacuum is providing. With #29 you will be able to configure the stats area to show any attribute depending on the state of the vacuum. 

For example if you wanted to add cleaning time to stats area when vacuum is cleaning you would add the following to your configration.

`stats:
  cleaning:
    - attribute: cleanTime
      unit: minutes
      subtitle: Cleaning Time`

**Comment by denysdovhan** [comment]
Should be resolved by #29. It will be released as 1.0.0.
