### ISSUE TITLE
Change background color? 

### ISSUE THREAD

**Issue by yvesdemoerloose** [denysdovhan/vacuum-card#309]
Hi,

Thx for the great work,. 
Is it somehow possible to change the background color? (default:blue) 
If not any possibility this can be implemented? 

Thx

**Comment by ValleBL** [comment]
You can use the [card_mod ](https://github.com/thomasloven/lovelace-card-mod)to do this:

`card_mod:
  style: |
    ha-card {
      border-radius: var(--ha-card-border-radius) !important;
    }
    ha-card.type-custom-vacuum-card div.preview {
      background: var( --ha-card-background)
    }`

**Comment by yvesdemoerloose** [comment]
Hi,

I actually tried this before opening an issue here and it didn't work. 
After your answer, I checked again and bumped into this on the card_mod page: 

_NOTE: card-mod only works on cards that contain a ha-card element. This includes almost every card which can be seen, but not e.g. conditional, entity_filter, vertical-stack, horizontal-stack, grid._

It was in a conditional card here...so that explains it. 

Thx for your reply, 
Kind regards

**Comment by stezak77** [comment]
@yvesdemoerloose try this:
```
style: |
  div.preview {background: red;}

```

![image](https://user-images.githubusercontent.com/49878007/145855721-7a5812b3-a548-4689-885f-e7089d9d13e2.png)

**Comment by stezak77** [comment]
@yvesdemoerloose you could remove the outer conditional card, and set your visibility conditions inside the style block, acting on the ha-card `display` CSS property.

For example:

```
style: |
  div.preview { background: red; }
  ha-card {
    {% if is_state('some_entity', 'some_state') %}
      display: block;
    {% else %}
      display: none;
    {% endif %}
  }
```

**Comment by spr0k3t** [comment]
I usually go into the /config/www/community/vacuum-card/vacuum.js and edit this to be something more aesthetically pleasing whenever there is an update that doesn't have to do with localization.  Also, because I use a custom image, I delete the gzipped file.  Could probably set this up on a watch file script to handle this for me so every time there is an actual update that isn't just localization, it would change the .preview{background: color;} div.

sed -i 's/background: var(--primary-color);/background: var(--background-color);/g' /config/www/community/vacuum-cardvacuum-card.js; rm -f  /config/www/community/vacuum-cardvacuum-card.js.gz

**Comment by vmartinv** [comment]
#337 maybe related
