### ISSUE TITLE
custom:vacuum-card disappears from the UI when the Dreame vac starts 

### ISSUE THREAD

**Issue by lviciedo** [denysdovhan/vacuum-card#604]
**Describe the bug**
custom:vacuum-card disappears from the UI when the Dreame vac starts then the card returns when vac has finished cleaning cycle

**Versions:**
Browser: chrome
Home Assistant 2023.9.1
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230908.0

**Comment by DevGoran** [comment]
Same issue here. Dissapears on both the HA android app and web browser (brave & firefox).

**Comment by Tamsy** [comment]
The issue seemingly does not only happen with the Dreame but also with the S5 Max (2 units here). Since many month already: As soon as the vacuums start the cards disapear on both the HA android app and web browser (brave, firefox, iron and palemoon).

**Comment by IDmedia** [comment]
I'm having the same issue with my normal S5. While my Dreame L10 Pro works fine. Once it starts cleaning the whole card is gone without any errors in the console. Once it changes state the card comes back.

**Comment by Pojox98** [comment]
I have same issue with dreame.vacuum.mc1808 (Xiaomi Mijia 1C Sweeping Vacuum Cleaner)

**Comment by IDmedia** [comment]
I think I solved this (for me at least). I found out that the m2 and Time spent sensors, which are only displayed while the vacuum is driving where missing/not working. Because of this the card disappeared every time the vacuum started cleaning. I made sure the sensors are working and the names are correct and now it seems to work again
