### ISSUE TITLE
State translations now work with standard states

### ISSUE THREAD

**Issue by deblockt** [denysdovhan/vacuum-card#85]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

State translations now work with standard states.
In french, states are not translated.

**Steps to reproduce**

1. Compare vacuum-card with home assistant default display

**Expected behavior**

Have same translation on vacuum card than home assistant 

**Screenshots**
![idle](https://user-images.githubusercontent.com/5050163/84415797-94430e00-ac13-11ea-82f4-66b3fdb737f5.png)
![cleaning](https://user-images.githubusercontent.com/5050163/84415803-96a56800-ac13-11ea-939e-bfa7862f4510.png)

**Comment by denysdovhan** [comment]
Can't reproduce this bug. What version of hass do you run?

**Comment by deblockt** [comment]
I use the version `0.110.2` with the proscenic 790T integration https://github.com/deblockt/hass-proscenic-790T-vacuum

**Comment by firstof9** [comment]
@deblockt The state should be ```docked``` when docked and charging, the status shown on the card should say ```charging``` because of the ```status``` attribute.

Example:
![image](https://user-images.githubusercontent.com/1105672/84597547-7d6e0880-ae19-11ea-88e1-866bd2f031b2.png)

What you are seeing is the ```status``` attribute not being translated.

**Comment by deblockt** [comment]
I understand the issue.
Where are you found the status list? I'm creating a proscenic vacuum integration and I'have not found any documentation about the status.

**Comment by deblockt** [comment]
I can see that on translation, you manage the following status:
 - Cleaning
 - Paused
 - Idle
 - Charging

What is displayed when the vacuum return to home? 

I can understand that by default `status` = `state`

**Comment by tibortiz** [comment]
@deblockt The state when the vacuum is inactive don't seems to be the same of all the vaccum.
For instance I have Roomba 960, the vaccum is always in "charging" state while docked.

The value displayed in the card is returned by the vaccum model integration in Home Assistant.
Maybe your vaccum move to Idle state when the battery is fully charged. Your vaccum integration created a vaccum entity in Home Assistant. You can find this entity via the Developer Tools > States and search for vaccum
![image](https://user-images.githubusercontent.com/25587210/85075194-12785500-b1be-11ea-984e-0debe0fcc0eb.png)

When i'm enabling French language in HA, the vaccum state translation in the card are still in English.I guess there is bug somewhere because when I'm editing my card with HA language in French I can see the vaccum card state in French but on my dashboard it's still in English

![image](https://user-images.githubusercontent.com/25587210/85075577-c7127680-b1be-11ea-9af0-99fb21e92f3a.png)

![image](https://user-images.githubusercontent.com/25587210/85075618-d85b8300-b1be-11ea-9bfc-050174ef3389.png)

**Comment by tibortiz** [comment]
Finally it's seems similar to #56 ?

**Comment by Nezumikun** [comment]
Hi!
Some states of my vacuum cleaner not equal states in localization files.
For example: my cleaner have state "Zoned cleaning", but in files consist only "segment cleaning".
Can you add this state in sources?
Cleaner model is Roborock S50 (not rooted)
![image](https://user-images.githubusercontent.com/50661/116860009-92a67e00-ac09-11eb-8345-61e65abd04ab.png)

**Comment by superpower10** [comment]
Same here for German. Some status are translated, other aren't. Like mop_washing etc.
